dispenserPickupBucketables: Fix where NBT data wasnt saved to the bucket
QuickCarpet/QuickCarpet pull request #103
Opened 2021-08-03 19:39 UTC by Coow

2021-08-08 06:21 UTC, JackTGG commented
Okay.

2021-08-17 10:12 UTC, skyrising requested changes

2021-08-17 10:12 UTC, skyrising commented on src/main/java/quickcarpet/feature/dispenser/PickupBucketablesBehavior.java
> +            if(first instanceof AxolotlEntity){
Why aren't you using `((Bucketable) first).copyDataToStack(stack)` here, but copy two implementations?

2021-08-17 10:12 UTC, skyrising commented on src/main/java/quickcarpet/feature/dispenser/PickupBucketablesBehavior.java
> +                Bucketable.copyDataToStack((MobEntity) first, stack);
The static `copyDataToStack` is deprecated, use the non-static one.

2021-08-17 13:04 UTC, skyrising approved these changes

2021-08-17 13:04 UTC, merged